version: "3.9"

services:
  # API principal iAcademicGenerator.API
  api:
    container_name: iacademic-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AcademicDb=Server=iAcademicGenerator.mssql.somee.com;Database=iAcademicGenerator;User Id=oscarvaldivieso_SQLLogin_1;Password=admin123;Encrypt=True;TrustServerCertificate=True;MultipleActiveResultSets=True
    ports:
      - "5000:8080"
    networks:
      - backend-net

  # API de UploadData
  upload:
    container_name: upload-api
    build:
      context: .
      dockerfile: UploadData.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AcademicDb=Server=iAcademicGenerator.mssql.somee.com;Database=iAcademicGenerator;User Id=oscarvaldivieso_SQLLogin_1;Password=admin123;Encrypt=True;TrustServerCertificate=True;MultipleActiveResultSets=True
    ports:
      - "5001:8080"
    networks:
      - backend-net

  # ðŸš€ API del ML Predictor
  mlapi:
    container_name: ml-api
    build:
      context: .
      dockerfile: AcademicOfferPredictor.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AcademicDb=Server=iAcademicGenerator.mssql.somee.com;Database=iAcademicGenerator;User Id=oscarvaldivieso_SQLLogin_1;Password=admin123;Encrypt=True;TrustServerCertificate=True;MultipleActiveResultSets=True
    ports:
      - "5002:8080"
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
